### ISSUE TITLE
Documentation for Magento Enterprise?

### ISSUE THREAD

**Issue by pstephenson02** [magento/devdocs-m1#35]
Hi. I'm working on a project that uses Magento Enterprise version 1.12.2.

I've already had problems with inconsistencies between this documentation: https://devdocs.magento.com/guides/m1x/magefordev/mage-for-dev-5.html and the version I'm running. Specifically, this issue bit me:
https://stackoverflow.com/questions/32989521/call-to-a-member-function-load-on-boolean-in-app-code-core-mage-core-model-ab

With the solution being that the structure of my config.xml was not correct.

Could you point me to where I could find specific documentation to the version I'm using?

Thanks

**Comment by dshevtsov** [comment]
@pstephenson02 we publish documentation for the latest version only. But you can use all the power of git and GitHub UI to dig into history of changes and find the version of topic you need. I did some search and the closest version of the topic I found is [this](https://github.com/magento/devdocs/blob/07fd609243d9c0405f12a93e3c5989da2e47761d/guides/m1x/magefordev/mage-for-dev-5.html).

**Comment by pstephenson02** [comment]
Thank you @dshevtsov. I'm happy to dig through the Git history, but what is the most reliable way to determine to which version of the framework the documentation refers?

I can see a line in the file you linked here: https://github.com/magento/devdocs/blob/07fd609243d9c0405f12a93e3c5989da2e47761d/guides/m1x/magefordev/mage-for-dev-5.html#L28
```html
<p><em>by Alan Storm</em>, updated for Magento 1.12</p>
```

Is that how you went about finding this commit?

**Comment by dshevtsov** [comment]
> Is that how you went about finding this commit?

Yes, I found a commit when this line was added.

Another marker you can use for 1.13+ versions is a commit when the version appeared in Release notes.

**Comment by pstephenson02** [comment]
Thank you 👍
